name: gozle_video_kids_v1
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  get_it: ^7.6.0
  cached_network_image: ^3.2.3
  flutter_bloc: ^8.1.3
  shimmer: ^3.0.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.8.1
  go_router: ^7.0.2
  flutter_secure_storage: ^8.0.0
  google_fonts: ^4.0.4
  url_launcher: ^6.1.11
  intl: ^0.18.0
  injectable: ^2.1.2
  flutter_localizations:
    sdk: flutter
  http: ^0.13.6
  dynamic_height_grid_view: ^0.0.3
  json_annotation: ^4.8.1
  video_player: ^2.7.0
  status_bar_control: ^3.2.1
  pin_code_fields: ^8.0.1
  flutter_keyboard_size: ^1.0.1
  flutter_keyboard_visibility: ^5.4.1
  audio_video_progress_bar: ^2.0.1
  lottie: ^2.7.0
  wakelock: ^0.6.2

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/gozle_icon.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/splash_images/
    - assets/icons/
    - assets/icons/errors/
    - assets/icons/lotties/
    - assets/
